export const projectsSection = {
  eyebrow: "02 / Selected systems",
  title: "Evidence, not a tool inventory.",
  description:
    "Three systems spanning product discovery, agentic AI, and privacy-preserving sensing—framed by the problem, engineering decisions, and evaluation approach.",
};

export const projects = [
  {
    id: "ecoshop",
    title: "EcoShop",
    status: "Production-shaped system",
    category: "Search · Ranking · Recommendation",
    positioning: "Production-shaped ML system for intelligent product discovery",
    summary:
      "An end-to-end e-commerce discovery platform combining semantic search, hybrid ranking, behavior-based recommendations, product comparison, and a conversational shopping assistant that answers questions about catalog products.",
    engineeringSummary:
      "EcoShop routes catalog data through semantic and keyword retrieval, hybrid ranking, personalized recommendations, and a REST API, while its catalog-grounded chatbot can discuss products, answer shopping questions, and support comparisons. Relevance is evaluated offline with Precision@K, Recall@K, MRR, and NDCG, while structured logging, health checks, and deterministic fallbacks keep the system observable and resilient when AI services fail.",
    image: "",
    imageAlt: "EcoShop product discovery application interface",
    imageWidth: 1200,
    imageHeight: 800,
    highlights: [
      "Hybrid semantic and keyword ranking",
      "Behavior-based personalized recommendations",
      "Offline evaluation with Precision@K, Recall@K, MRR, and NDCG",
      "Dockerized deployment with observability and graceful AI fallbacks",
    ],
    architecture: ["Product catalog", "Embeddings + keywords", "Hybrid ranker", "Recommendations", "REST API", "Evaluation"],
    evidence: [
      { label: "Relevance", value: "Precision@K · Recall@K · MRR · NDCG" },
      { label: "Operations", value: "Structured logs · request IDs · health checks" },
      { label: "Resilience", value: "Deterministic fallbacks for AI-provider failures" },
    ],
    technologyGroups: [
      {
        label: "Machine Learning",
        items: ["Python", "Gemini"],
      },
      {
        label: "Application",
        items: ["Django REST Framework", "React", "PostgreSQL"],
      },
      {
        label: "Deployment",
        items: ["Docker", "Nginx"],
      },
    ],
    repositoryUrl: "",
    liveUrl: "https://ecoshop.dev",
    caseStudyUrl: "",
    publicationUrl: "",
    featured: true,
    details: {},
  },
  {
    id: "cortex",
    title: "CORTEX",
    status: "In development",
    category: "Agentic AI · Multimodal workflows",
    positioning: "A model-flexible workspace for agentic document and image workflows",
    summary:
      "An agentic AI application designed to work across multiple models, process documents and images, call functions and tools, connect through MCP, and maintain memory across workflows.",
    engineeringSummary:
      "CORTEX is being designed around a model router and agent runtime that can coordinate multimodal inputs, tools, MCP services, and persistent memory. Its detailed retrieval, evaluation, and deployment architecture will be documented as the system matures.",
    image: "",
    imageAlt: "",
    imageWidth: null,
    imageHeight: null,
    highlights: [
      "Model-flexible orchestration",
      "Document and image processing",
      "Function calling and tool use",
      "MCP connections and persistent memory",
    ],
    architecture: ["Documents + images", "Model router", "Agent runtime", "Tools + MCP", "Memory", "Response"],
    evidence: [],
    technologyGroups: [
      {
        label: "Confirmed scope",
        items: ["Multimodal input", "Function calling", "Tool calling", "MCP", "Memory"],
      },
    ],
    repositoryUrl: "",
    liveUrl: "https://cortex.dev",
    caseStudyUrl: "",
    publicationUrl: "",
    featured: true,
    details: {
      problem: "",
      documentSources: [],
      retrievalArchitecture: "",
      chunking: "",
      embeddings: "",
      vectorDatabase: "",
      reranking: "",
      citations: "",
      toolCalling: "",
      langChain: "",
      langGraph: "",
      agentState: "",
      evaluation: "",
      deployment: "",
      limitations: [],
    },
  },
  {
    id: "edgefusion-act",
    title: "Privacy-Preserving Multimodal Activity Recognition",
    status: "Completed doctoral research",
    category: "Multimodal ML · Edge AI",
    positioning: "Non-visual multimodal AI for smart-home activity recognition",
    summary:
      "A multimodal machine learning system that combines mmWave radar and electricity signals to recognize Activities of Daily Living without continuous video recording.",
    engineeringSummary:
      "The system encodes radar and electricity time series before applying cross-modal fusion for activity recognition. It was evaluated across scripted, cross-subject, and free-living settings, with lightweight temporal modeling and quantization explored for privacy-conscious edge inference.",
    image: "",
    imageAlt: "Privacy-preserving multimodal activity recognition project",
    imageWidth: 1200,
    imageHeight: 700,
    highlights: [
      "Radar and electricity sensor fusion",
      "Cross-modal and event-aware attention",
      "Lightweight temporal modeling and quantization",
      "Evaluation across scripted, cross-subject, and free-living settings",
    ],
    architecture: ["mmWave radar", "Electricity signals", "Temporal encoders", "Cross-modal fusion", "Activity recognition"],
    evidence: [
      { label: "Protocol", value: "Scripted · cross-subject · free-living" },
      { label: "Privacy", value: "Non-visual sensing in place of continuous video" },
      { label: "Efficiency", value: "Lightweight temporal modeling · quantization" },
    ],
    technologyGroups: [
      {
        label: "Machine Learning",
        items: ["Python", "PyTorch", "Transformers", "Temporal CNNs", "Multimodal Learning"],
      },
      {
        label: "Sensing",
        items: ["mmWave Radar", "NILM"],
      },
      {
        label: "Deployment-oriented",
        items: ["Edge AI"],
      },
    ],
    repositoryUrl: "",
    liveUrl: "",
    caseStudyUrl: "#/phd-research",
    publicationUrl: "",
    featured: true,
    details: {},
  },
  {
    id: "nilm-analyzer",
    title: "NILM Analyzer",
    positioning: "",
    summary:
      "A modular NILM toolkit with harmonized datasets, PyTorch models, and realtime energy disaggregation dashboards.",
    image: "",
    imageAlt: "NILM Analyzer project interface",
    imageWidth: 1200,
    imageHeight: 800,
    highlights: [],
    technologyGroups: [],
    repositoryUrl: "",
    liveUrl: "",
    caseStudyUrl: "",
    publicationUrl: "",
    featured: false,
    details: {},
  },
  {
    id: "groqflow",
    title: "GroqFlow",
    positioning: "",
    summary:
      "A real-time AI chatbot platform powered by Groq LLMs, featuring streaming responses, conversation persistence, and a ChatGPT-style UI.",
    image: "",
    imageAlt: "GroqFlow chatbot application interface",
    imageWidth: 1200,
    imageHeight: 800,
    highlights: [],
    technologyGroups: [],
    repositoryUrl: "",
    liveUrl: "https://pourya-moghadam74.github.io/chatbot/",
    caseStudyUrl: "",
    publicationUrl: "",
    featured: false,
    details: {},
  },
];
