export const publications = [
  {
    id: "kidney-graft-failure-red-deer",
    title:
      "A Machine Learning Framework to Predict Kidney Graft Failure with Class Imbalance Using Red Deer Algorithm",
    authors: ["P. Moghadam", "A. Ahmadi"],
    year: "2022",
    venue: "Expert Systems with Applications, 210, 118515",
    status: "published",
    publicationUrl: "",
    pdfUrl: "",
    githubUrl: "",
    featured: true,
  },
  {
    id: "red-deer-data-clustering",
    title: "A Novel Two-Stage Bio-Inspired Method Using Red Deer Algorithm for Data Clustering",
    authors: ["P. Moghadam", "A. Ahmadi"],
    year: "2024",
    venue: "Evolutionary Intelligence, 17(3), 1819–1836",
    status: "published",
    publicationUrl: "",
    pdfUrl: "",
    githubUrl: "",
    featured: true,
  },
  {
    id: "nilm-cross-country-generalization",
    title:
      "Non-Intrusive Load Monitoring for Smart Residential Buildings: An AI-Based Framework with Cross-Country Generalization",
    authors: ["P. Moghadam", "A. Roshan Fekr"],
    year: "2026",
    venue: "Energy and Buildings, 117632",
    status: "published",
    publicationUrl: "",
    pdfUrl: "",
    githubUrl: "",
    featured: true,
  },
  {
    id: "adl-monitoring-review",
    title:
      "AI-Driven Activity of Daily Living Monitoring: A Comprehensive Review of Ambient, Wearable, and Fusion-Based Sensing Technologies",
    authors: ["P. Moghadam", "A. Roshan Fekr"],
    year: "2026",
    venue: "Annals of Biomedical Engineering, 1–35",
    status: "published",
    publicationUrl: "",
    pdfUrl: "",
    githubUrl: "",
    featured: true,
  },
  {
    id: "structural-locality-point-clouds",
    title: "Structural Locality: Learning Neighborhoods Beyond Spatial Proximity in Point Clouds",
    authors: ["P. Moghadam", "A. Roshan Fekr"],
    year: "",
    venue: "Neurocomputing",
    status: "submitted",
    publicationUrl: "",
    pdfUrl: "",
    githubUrl: "",
    featured: false,
  },
  {
    id: "mc-former",
    title: "MC-Former: Interaction-Aware Action Recognition via Hand-Object Motion Coupling",
    authors: ["P. Moghadam", "A. Roshan Fekr"],
    year: "",
    venue: "Pattern Recognition",
    status: "submitted",
    publicationUrl: "",
    pdfUrl: "",
    githubUrl: "",
    featured: false,
  },
  {
    id: "efact",
    title:
      "EFACT: Attention-Based Cross-Modal Temporal Modeling for Fine-Grained Activity Recognition Using RGB-D Data",
    authors: ["P. Moghadam", "A. Roshan Fekr"],
    year: "",
    venue: "Neurocomputing",
    status: "submitted",
    publicationUrl: "",
    pdfUrl: "",
    githubUrl: "",
    featured: false,
  },
  {
    id: "e2r-fusenet",
    title:
      "E2R-FuseNet: Privacy-Preserving Activity Recognition via Asymmetric Fusion of mmWave Radar and Electricity Signals",
    authors: ["P. Moghadam", "A. Roshan Fekr"],
    year: "",
    venue: "Biomedical Signal Processing and Control",
    status: "submitted",
    publicationUrl: "",
    pdfUrl: "",
    githubUrl: "",
    featured: false,
  },
  {
    id: "drift-aware-adaptive-nilm",
    title:
      "Drift-Aware Adaptive Non-Intrusive Load Monitoring Based on Hybrid Meta-Continual Feature Learning for Edge Energy Systems",
    authors: ["P. Moghadam", "A. Roshan Fekr"],
    year: "",
    venue: "Applied Soft Computing",
    status: "submitted",
    publicationUrl: "",
    pdfUrl: "",
    githubUrl: "",
    featured: false,
  },
];
